### PR TITLE
Sentencepiece

### PR DESCRIPTION
**Pull request by gandroz**
I wanted to add the sentencepiece featurizer from Google instead of using subword on tensorflow when training a conformer.

### CODE REVIEW

**Comment by usimarit** [comment]
Please get the newest code and resolve conflicts :smile:

**Comment by usimarit** [comment]
Hi @gandroz, thank you for your contribution, I have some suggestions:

Firstly,
These lines:
```python
def __init_upoints(self):
    text = [""]
    for idx in range(1, self.num_classes):
        text.append(self.model.decode_ids([idx]))
    self.upoints = tf.strings.unicode_decode(text, "UTF-8")
    self.upoints = self.upoints.to_tensor()  # [num_classes, max_subword_length]
```
Are used when the `blank = 0` (which is the `text = [""]`). Can you either update the blank to 0 or update this function please.

Secondly, why do you repeat the class `SentencePieceFeaturizer` twice?

**Comment by gandroz** [comment]
Hmmm the duplicate was apparently due to a merge conflict, sorry.
I also corrected the blank to use the `PAD` tag of `sentencepiece`. I noticed the blank is hard-coded to 0, maybe it could be configurable of class-dependent ?
Finally, I added some tests to be sure the featurizer is consistent with the subword featurizer.

**Comment by usimarit** [comment]
@gandroz The blank is not hard-coded to 0, only the **unicode points** have the blank is always 0, which is the NULL character `\000`. The `upoints` is an array which indices are the ids, if the blank is the id `3` then the `upoints[3] = 0`. The purpose of `upoints` is to support tflite to decode to Unicode Points instead of ids or string (tf.string is not supported yet in tflite) and in the future it might be used for multi-languages ASR.

**Comment by usimarit** [comment]
About this [file](https://github.com/TensorSpeech/TensorFlowASR/blob/ac4ed5e3ebf1fb7bd138606cc87bb42a4e7c1fbc/vocabularies/conformer.subwords). You should name it as the corpus that you create subwords from :smile:

**Comment by usimarit** [comment]
@gandroz Please change the name of the `vocabularies/conformer.subwords` :smile:

**Comment by gandroz** [comment]
@usimarit actually, it is your file which stands in your Drive that I used to perform some (unit)tests

**Comment by usimarit** [comment]
@gandroz Oh I see :smile: But that file contains subwords from test-clean too, so it's not quite true, you should use the `vocabularies/librispeech_train_4_1030.subwords` and remove that `vocabularies/conformer.subwords`

**Comment by gandroz** [comment]
@usimarit ok no problem. Anyway, that's just for some tests ;) not for performances

**Comment by usimarit** [comment]
@gandroz I just want to remove unnecessary components to keep the repo clean :smile:

**Review by usimarit — APPROVED** [review]

**Pull request merged**
